---
#-------------------------------
# General Site Settings

title: Byron Chung
logo:
author: themefisher
description: this is meta description
email: bholdenchung@gmail.com
phone: +1 647 710 9949
address: github.com/byronchung <br> linkedin.com/in/byronchung
copyright: Copyright &copy; 2022 Byron Chung 

menu:
  - { name: About, link: "/about" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! My name is Byron! <br> Software Developer

social:
  - { icon: "ti-facebook", link: "#" }
  - { icon: "ti-instagram", link: "#" }
  - { icon: "ti-dribbble", link: "#" }
  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section

# About Page

# Work Process Section
work-process:
  - title: "GitHub"
    icon: "assets/images/icons/github.png"
    content: Testing

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section

#-------------------------------
# Skills Section


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Software Developer Intern,
      icon: "UWO.png",
      date: "May 2022 - Aug. 2022",
      organization: "Western University",
    }
  - {
      name: Software Developer Intern,
      icon: "cheapreats.png",
      date: "Sept. 2021 - April 2022",
      organization: "CheaprEats",
    }
 
#-------------------------------
# Education Section

#-------------------------------
# Services Section

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/mirror.png"
    url: "https://github.com/ByronChung/Raspberry-Pi-Interactive-Mirror"

  - image: "assets/images/portfolio/presence.png"
    url: "https://github.com/ByronChung/Presence"

  - image: "assets/images/portfolio/pathfinder.png"
    url: "https://github.com/ByronChung/Pathfinding-Visualizer"

  - image: "assets/images/portfolio/forest_guardian.png"
    url: "https://github.com/ByronChung/Forest-Guardian-Game"

  - image: "assets/images/portfolio/country_statistics.png"
    url: "https://github.com/ByronChung/Country-Statistics"

# Portfolio Page
portfolio-label:
  - { title: "UI/UX Design", type: "design" }
  - { title: "BRANDING", type: "branding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/forest_guardian.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Testimonials Section

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: steve.fruits@email.com
